export const colombianData = [
    { id: "AMA", department: "Amazonas", cities: ["Leticia", "Puerto Nariño"] },
    { id: "ANT", department: "Antioquia", cities: ["Medellín", "Bello", "Envigado", "Itagüí", "Rionegro"] },
    { id: "ARA", department: "Arauca", cities: ["Arauca", "Saravena", "Tame"] },
    { id: "ATL", department: "Atlántico", cities: ["Barranquilla", "Soledad", "Malambo"] },
    { id: "BOG", department: "Bogotá D.C.", cities: ["Bogotá"] },
    { id: "BOL", department: "Bolívar", cities: ["Cartagena", "Magangué", "Turbaco"] },
    { id: "BOY", department: "Boyacá", cities: ["Tunja", "Duitama", "Sogamoso"] },
    { id: "CAL", department: "Caldas", cities: ["Manizales", "La Dorada", "Chinchiná"] },
    { id: "CAQ", department: "Caquetá", cities: ["Florencia", "San Vicente del Caguán"] },
    { id: "CAS", department: "Casanare", cities: ["Yopal", "Aguazul", "Villanueva"] },
    { id: "CAU", department: "Cauca", cities: ["Popayán", "Santander de Quilichao"] },
    { id: "CES", department: "Cesar", cities: ["Valledupar", "Aguachica", "Agustín Codazzi"] },
    { id: "CHO", department: "Chocó", cities: ["Quibdó", "Istmina"] },
    { id: "COR", department: "Córdoba", cities: ["Montería", "Cereté", "Sahagún"] },
    { id: "CUN", department: "Cundinamarca", cities: ["Soacha", "Fusagasugá", "Facatativá", "Zipaquirá", "Chía", "Girardot"] },
    { id: "GUA", department: "Guainía", cities: ["Inírida"] },
    { id: "GUV", department: "Guaviare", cities: ["San José del Guaviare"] },
    { id: "HUI", department: "Huila", cities: ["Neiva", "Pitalito", "Garzón"] },
    { id: "LAG", department: "La Guajira", cities: ["Riohacha", "Maicao", "Uribia"] },
    { id: "MAG", department: "Magdalena", cities: ["Santa Marta", "Ciénaga", "Fundación"] },
    { id: "MET", department: "Meta", cities: ["Villavicencio", "Acacías", "Granada"] },
    { id: "NAR", department: "Nariño", cities: ["Pasto", "Tumaco", "Ipiales"] },
    { id: "NSA", department: "Norte de Santander", cities: ["Cúcuta", "Ocaña", "Pamplona"] },
    { id: "PUT", department: "Putumayo", cities: ["Mocoa", "Puerto Asís", "Orito"] },
    { id: "QUI", department: "Quindío", cities: ["Armenia", "Calarcá", "Salento"] },
    { id: "RIS", department: "Risaralda", cities: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal"] },
    { id: "SAP", department: "San Andrés y Providencia", cities: ["San Andrés"] },
    { id: "SAN", department: "Santander", cities: ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja", "San Gil"] },
    { id: "SUC", department: "Sucre", cities: ["Sincelejo", "Corozal", "Tolú"] },
    { id: "TOL", department: "Tolima", cities: ["Ibagué", "Espinal", "Melgar"] },
    { id: "VAC", department: "Valle del Cauca", cities: ["Cali", "Buenaventura", "Palmira", "Tuluá", "Buga"] },
    { id: "VAU", department: "Vaupés", cities: ["Mitú"] },
    { id: "VID", department: "Vichada", cities: ["Puerto Carreño"] },
].sort((a, b) => a.department.localeCompare(b.department));
